### ISSUE TITLE
Don't analyse Kotlin files generated by kapt

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt-compiler-plugin#10]
Since they're also compiled by the Kotlin compiler they're included in the collection of files provided to `analysisCompleted` function, and detekt will analyse them. Because they're generated files, there's little that can be done about incorrect formatting.

**Comment by 3flex** [comment]
I think the best approach is to support global path filtering, so some files can be excluded from analysis.

This can be either self-contained in detekt-compiler-plugin (I can submit a PR for this) or pass all files + filter rules through to detekt via detekt-tooling, but I think this requires changes in detekt because exclude rules passed to detekt are only used in `KtTreeCompiler` which isn't used by the compiler plugin.

**Comment by BraisGabin** [comment]
I think that these files should be always filtered so I don't think that we should use the config to filtered them.

The code smells in generated code doesn't have sense. The generated code can be really hacky to get some performance.

**Comment by 3flex** [comment]
>  I don't think that we should use the config to filtered them

I agree, but the kapt sources directory is configurable, so we'd need to figure out how to get the value the sources directory is set to. Of course in majority of cases it will be default `build/generated` directory but not always, so I thought a manual filter would be easier for now.

**Comment by arturbosch** [comment]
We should probably check if the KtFile has a `isGenerated` modifier somewhere so we can simple exclude all generated code as soon as possible?

**Comment by 3flex** [comment]
I've looked at KtFile but I can't see any `isGenerated` modifier or similar. Which makes sense, since the compiler doesn't care whether sources are generated or not, it just compiles whatever is provided to it.

There's good news for kapt though - the kapt Gradle plugin hard codes the Kotlin sources output directory to `${project.buildDir}/generated/source/kaptKotlin/$sourceSetName`. That's easy to whitelist.

However as soon as I started testing that I realised there are other plugins that can generate code. SQLDelight for example generates code but not with kapt, and the output goes in a different directory (`${project.buildDir}/generated/sqldelight/code/$name`). So we still need the ability to globally filter certain directories since we can't handle every possible code-generating plugin.

So I propose:
1. A flag for kapt, set to false by default. When flag is false, the kapt Kotlin generated sources will not be scanned, when it's true, it will be. I think kapt deserves special treatment with a flag because it's part of the Kotlin project, but should be excluded by default.
2. A separate input option for glob patterns to globally exclude files from analysis. That can be used for other code-generating plugins like SQLDelight.

I'm happy to raise PRs for both of these if implementation sits in detekt-compiler-plugin. But maybe they belong in detekt-core?

**Comment by BraisGabin** [comment]
Nice research. I agree with you that we need both points. 

I think that this is not detekt-core work. The clients should tell it what files to parse. So I think that it should be implemented here.

And I don't know why should we want a flag to allow the user to scan the files generated by kapt. I would not implement that flag. And, if someone opens an issue with a good use case for it we can add it later. This way we keep the configuration as easy as possible.

**Comment by 3flex** [comment]
I agree clients should pass only the files that need analysis to detekt core - I'll create that PR for filtering in this plugin. I do think detekt-core or detekt-cli needs support for global file filtering too but at least detekt-gradle-plugin can already filter files so the most used clients will support filtering.

I'll add a kapt filter that applies by default. It will be possible to remove that filter without a flag. That should be OK for any advanced users who actually want to scan kapt-generated files (I was thinking maybe kapt plugin writers might want detekt to scan generated files to make sure the output is clean but anyone doing that can just remove the kapt filter in the Gradle config).
