### ISSUE TITLE
isEnabled should be true by default

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt-compiler-plugin#12]
In majority of cases, anyone applying this plugin to the compiler would want the plugin to run - I can't think of any other Gradle plugin that doesn't run when it's been added to the build, and it doesn't make sense to have this flag on the CLI at all.

I very strongly believe that this flag should be removed, or at the very least, changing the default to "true".

**Comment by arturbosch** [comment]
I believe there should be an option to disable our compiler plugin without changing the gradle build file.
So changing this to true by default is good for me.

**Comment by 3flex** [comment]
Reopened - see #20

**Comment by arturbosch** [comment]
`IsEnabled` is already true by default:

https://github.com/detekt/detekt-compiler-plugin/blob/cb28aa69af362c9d30c779c7fd9313ae6db178f3/src/main/kotlin/io/github/detekt/gradle/extensions/DetektExtension.kt#L10-L11
