### ISSUE TITLE
buildUponDefaultConfig should be true by default

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt-compiler-plugin#13]
We'd briefly discussed this in another issue, but I can't think of a good reason for this to be false by default in a new plugin.

Even if this isn't done now, I'm just opening this issue so it can be tracked.

I've already started using this plugin on an Android project, and it's so convenient to use! But to get the most people using it, keep the configuration minimal. It should be as simple as this to start getting value from it:

```gradle
plugins {
    id("io.github.detekt.gradle.compiler-plugin")
}

apply plugin: "detekt-compiler-plugin"
```

**Comment by arturbosch** [comment]
Agree, as we do now say this is the new default plugin for now and it has a leading 0, lets go with this option by default.

**Comment by 3flex** [comment]
Reopened - see #20
