### ISSUE TITLE
Show the rule that triggered a warning

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt-compiler-plugin#14]
The output shows the rule's message, which is useful, but if I ran this in isolation I wouldn't know which rule I'm breaking without searching around on the detekt doc site.

![image](https://user-images.githubusercontent.com/170028/92297834-9ef90f00-ef86-11ea-803f-ac04ce8c5cb9.png)

I think it would be useful if the message was prefixed with the provider and rule:
> potential-bugs/UnsafeCallOnNullableType: Calling !! on a nullable type will throw a NullPointerException at runtime in case the value is null. It should be avoided.

Or just the rule:
> UnsafeCallOnNullableType: Calling !! on a nullable type will throw a NullPointerException at runtime in case the value is null. It should be avoided.

But the first one makes it super simple to identify what has to be added to the config to disable the rule if I didn't like it.

**Comment by BraisGabin** [comment]
I think that this should be fixed at detekt level. My colleagues always ask me which suppress should they use to ignore an issue. And it's not a trivial question.

I will vote to add just the name of the rule.

**Comment by arturbosch** [comment]
Mh, detekt prints the rule id on the console? The IntelliJ plugin prepends the rule id before the message.
Do I miss something?

Yes, the compiler plugin does not prepend the rule id for now but should like the intellij plugin.
