### ISSUE TITLE
detekt analysis doesn't run when changing config after clean compile

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt-compiler-plugin#16]
What happens:
* Run compile Kotlin task with `allWarningsAsErrors = true`: FAIL
  * detekt identifies issues
  * Fix issues
* Run compile Kotlin task with `allWarningsAsErrors = true`: SUCCESS
* Change detekt config - enable new rules that should fail build
* Run compile Kotlin task with `allWarningsAsErrors = true`: SUCCESS

What should happen:
* Run compile Kotlin task with `allWarningsAsErrors = true`: FAIL
  * detekt identifies issues
  * Fix issues
* Run compile Kotlin task with `allWarningsAsErrors = true`: SUCCESS
* Change detekt config - enable new rules that should fail build
* Run compile Kotlin task with `allWarningsAsErrors = true`: FAIL
  * detekt identifies issues
  * Fix issues

Why? Because the subplugin input is the config file path(s), the compiler is not aware of the config file contents, so it will not rerun the compilation if the config file contents change.

Probably calculating hash value for the config file content passed in and providing that as a compiler input will fix this, since the hash will change when the config file content changes.

**Comment by 3flex** [comment]
Please vote for [KT-41711](https://youtrack.jetbrains.com/issue/KT-41711) which will hopefully result in direct support for this use case to be added to the Kotlin Gradle plugin API.

**Comment by arturbosch** [comment]
Thx, I've voted.
